### ISSUE TITLE
getUserMedia() no longer works on insecure origins.

### ISSUE THREAD

**Issue by normanr** [soundstep/magic-xylophone#1]
getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by normanr** [comment]
@soundstep I just wanted to check if you have plans to redeploy at a working https url?  I ended up just using github's pages with the master branch, which if once enabled would make the app available at https://soundstep.github.io/magic-xylophone/app/ I think.

**Comment by soundstep** [comment]
Very good idea, I'll do that! Thanks for the suggestion.
